# Generated by Django 4.0 on 2024-03-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_level_question_result_subject_alter_quiz_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
