# Generated by Django 4.0 on 2024-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueregistrationcode',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('USED', 'Used')], default='AVAILABLE', max_length=20),
        ),
    ]
